# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = ""
  weight = 1

# [[main]]
#  name = "Publications"
#  url = "#publications_featured"
#  weight = 2

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 4

[[main]]
  name = "Tags"
  url = "#tags"
  weight = 5

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 3

[[main]]
  name = "About"
  url = "#about"
  weight = 6

# [[main]]
#  name = "Tutorials"
#  url = "/tutorial/"
#  weight = 5

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 7


[[main]]
  name = "RSS"
  url = "/index.xml"
  weight = 8


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 7
